### ISSUE TITLE
Arquivo de log

### ISSUE THREAD

**Issue by filhodanuvem** [vieiratn/estudos-python#3]
Quando fazemos aplicações grandes temos um conceito de logs. Resumindo muito um arquivo de log é um arquivo que salva eventos importantes do sistema (algum erro aconteceu quando um usuario utilizava o sistema? Como eu posso investigar no futuro o que aconteceu?). 

Poderíamos usar esse conceito e cada vez que o usuario fizer algo errado no sistema, adicionamos uma linha em um arquivo `erros.log` .

**Comment by vieiratn** [comment]
Melhoria implementada.
