### ISSUE TITLE
off topic

### ISSUE THREAD

**Issue by filhodanuvem** [vieiratn/estudos-python#4]
Hey Thiago, de novo parabéns pela dedicação nos estudos 💪🏾, mas to passando pra dizer que vou mostrar esse projeto num vídeo para inspirar outros inscritos do canal.  Se você ver o vídeo e eu apontar alguma possivel melhoria pequena, não desenvolva ela para dar chance para que outras pessoas venham aqui e estudem praticando também 😉. 

Obs: fecha a issue quando ler isso.

**Comment by vieiratn** [comment]
Okay!
